title: Testing the Waters on Coding
author: ctmeeks22
email: chrismeeks92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just me tring to learn the basics of Coding and such. Thinking about learning
  to build websites so when i start my Personal Training i can create my own
  website and build it how i want. If thats even how it works lol. 

# social links
twitter_username: chrismeeks92
github_username:  ctmeeks22

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate